default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    match(
      type: "appstore",
      app_identifier: "com.7HWULNV59K.PrivateJetManager",
      api_key: api_key,
      git_url: "https://#{ENV["MATCH_GIT_TOKEN"]}@github.com/nini5182/Match-Secrets.git",
      readonly: true
    )

    build_app(
  scheme: "PrivateJetManager",
  export_method: "app-store",
  export_options: {
    signingStyle: "manual",
    provisioningProfiles: {
      "com.7HWULNV59K.PrivateJetManager" => "match AppStore com.7HWULNV59K.PrivateJetManager"
    }
  }
)

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
