default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    build_app(
      scheme: "PrivateJetManager",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
