default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "PrivateJetManager"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
